# Generated by Django 5.1.4 on 2025-01-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'productcategories'},
        ),
    ]
