# Generated by Django 5.1.4 on 2025-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop_app', '0002_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'product  categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
