# Generated by Django 5.1.4 on 2025-01-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop_app', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
    ]
