# Generated by Django 5.1.4 on 2025-01-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop_app', '0008_rename_text_product_description_product_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price_for_cart', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order_list', models.JSONField()),
            ],
        ),
    ]
