# Generated by Django 5.1.4 on 2025-01-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop_app', '0011_rename_order_list_order_order_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
