# Generated by Django 4.2.18 on 2025-01-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop_app', '0012_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
