# Generated by Django 4.2.18 on 2025-01-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop_app', '0013_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
